# Generated by Django 3.2.5 on 2021-07-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_car_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mark',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
